### ISSUE TITLE
wrong admin for some addresses

### ISSUE THREAD

**Issue by nlehuby** [pelias/wof-admin-lookup#179]
Hello,

I have some issues with addresses in the wrong locality :

For instance 
https://mapzen.com/search/explorer/?query=search&text=111%20Boulevard%20de%20Loz%C3%A8re%20palaiseau  is ko
the expected address is https://mapzen.com/search/explorer/?query=place&ids=openaddresses%3Aaddress%3Afr%2Fessonne%3Ad3ecb2bfe6ff07b1
I guess it cannot be found because, according to Pelias, it is in the city of [Villebon-sur-Yvette](https://whosonfirst.mapzen.com/spelunker/id/101751043/) whereas it should be in the city of [Palaiseau](https://whosonfirst.mapzen.com/spelunker/id/404401133/)

This is quite strange, because according to Spelunker, the address really seems:
* in the shape of Palaiseau
* not in the shape of Villebon-sur-Yvette

Same issue with this street : 
https://mapzen.com/search/explorer/?query=place&ids=openstreetmap%3Astreet%3Apolyline%3A5393400
https://mapzen.com/search/explorer/?query=search&text=rue%20du%20regard%20palaiseau

**Comment by nlehuby** [comment]
Same issue with this address : 
https://mapzen.com/search/explorer/?query=search&text=3%20Place%20L%C3%A9on%20Deubel%20paris

Expected is https://mapzen.com/search/explorer/?query=place&ids=openaddresses%3Aaddress%3Afr%2Fparis%3Aba346bf83c26b7b4

And it shoud not be in [Boulogne-Billancourt](https://whosonfirst.mapzen.com/spelunker/id/102071913/) according to the shape

**Comment by missinglink** [comment]
that's odd.. originally I thought that maybe the polygon data changed since our last build, but looking at the commits on Github that doesn't seem to be the case [1](https://github.com/whosonfirst-data/whosonfirst-data/blame/master/data/101/751/043/101751043.geojson) [2](https://github.com/whosonfirst-data/whosonfirst-data/blame/master/data/404/401/133/404401133.geojson).

using another point-in-polygon system with fresh data, I got:
```{ lat: 48.706181, lon: 2.226639 }```

|placetype|name|id|
|--|--|--|
|planet|Earth|0|
|continent|Europe|102191581|
|empire|France|136253037|
|timezone|Europe/Paris|102047881|
|country|France|85633147|
|macroregion|Ile-of-France|404227465|
|region|Essonne|85683371|
|macrocounty|Palaiseau|404228183|
|county|Palaiseau|102068485|
|localadmin|Palaiseau|404401133|
|locality|Palaiseau|101751001|
|postalcode|91120|421309367|
|neighbourhood|Villiers|85794679|

but on our production servers I get:

```javascript
curl localhost:3102/2.226639/48.706181

{
  "continent": [
    {
      "id": 102191581,
      "name": "Europe",
      "centroid": {
        "lat": 55.924452,
        "lon": 28.09812
      },
      "bounding_box": "-24.539906,34.815009,69.033946,81.85871"
    }
  ],
  "country": [
    {
      "id": 85633147,
      "name": "France",
      "abbr": "FRA",
      "centroid": {
        "lat": 42.171601,
        "lon": -2.770525
      },
      "bounding_box": "-61.797076,-21.370839,55.855019,51.087167"
    }
  ],
  "county": [
    {
      "id": 102070589,
      "name": "Villebon-Sur-Yvette",
      "centroid": {
        "lat": 48.687407,
        "lon": 2.255144
      },
      "bounding_box": "2.19545645914,48.6575852124,2.30515701885,48.7182787392"
    }
  ],
  "localadmin": [
    {
      "id": 404407569,
      "name": "Villebon-Sur-Yvette",
      "centroid": {
        "lat": 48.695678,
        "lon": 2.235053
      },
      "bounding_box": "2.20470708443,48.6849419137,2.26819330215,48.7072139628"
    }
  ],
  "locality": [
    {
      "id": 101751043,
      "name": "Villebon-sur-Yvette",
      "centroid": {
        "lat": 48.696695,
        "lon": 2.230193
      },
      "bounding_box": "2.204689,48.6851045,2.2596385,48.7081375"
    }
  ],
  "macrocounty": [
    {
      "id": 404228183,
      "name": "Palaiseau",
      "centroid": {
        "lat": 48.655049,
        "lon": 2.222647
      },
      "bounding_box": "2.01165781835,48.5186587673,2.4142601104,48.7761020316"
    }
  ],
  "macroregion": [
    {
      "id": 404227465,
      "name": "Ile-of-France",
      "centroid": {
        "lat": 48.709279,
        "lon": 2.503397
      },
      "bounding_box": "1.4467435,48.120537,3.558455,49.241062"
    }
  ],
  "neighbourhood": [
    {
      "id": 85794679,
      "name": "Villiers",
      "centroid": {
        "lat": 48.69487,
        "lon": 2.247843
      },
      "bounding_box": "2.20099853516,48.635613099,2.29240966797,48.742643799"
    }
  ],
  "region": [
    {
      "id": 85683371,
      "name": "Essonne",
      "centroid": {
        "lat": 48.52261,
        "lon": 2.243428
      },
      "bounding_box": "1.9146685,48.284466,2.5852695,48.7761"
    }
  ]
}
```

**Comment by missinglink** [comment]
cc/ @trescube @orangejulius any ideas?

**Comment by orangejulius** [comment]
Hi @nlehuby,
Thank you for reporting this. After some investigation I determined this is mostly due to the design of our point in polygon implementation, but I believe we can resolve it with the help of our data team.

A little background: we don't actually perform full point in polygon for every layer (locality, country, continent, etc) if we can avoid it. Instead we do a point in polygon lookup at the lowest layer, and if we find a record, we use the Who's on First hierarchy for that record. This is a lot faster than doing more point in polygon lookups, and can also be more correct in the case where the local administrative organization doesn't match up perfectly with the purely mathematical geometries.

Usually, the first layer we find a result for is `neighbourhood`, and in this case you can see we have a neighbourhood in the results from the point in polygon service that @missinglink posted. If you go to the [spelunker record for Villiers](https://whosonfirst.mapzen.com/spelunker/id/85794679/) you might see the problem immediately.

![image](https://user-images.githubusercontent.com/111716/33439450-731b8db4-d5bb-11e7-9769-f33ed87d87fa.png)

As you can see the geometry for this neighbourhood covers a huge area, including most of Villebon-sur-Yvette and Palaiseau, and the centroid falls in Villebon-sur-Yvette. My guess is this geometry is not correct.

A lot of neighbourhoods were actually generated programatically with checkin data from Foursquare many years ago (the giveaway is the bubbly shape where relatively few checkins resulted in a massive geometry), and I believe that's the case here.

Anyways, we can resolve this in a few ways:
1. Marking the geometry as invalid and possibly deleting it in WOF, or replacing it with a more correct one if it exists
2. If the neighbourhood doesn't exist at all maybe we can just delete it or mark it as "suspect"

I'd love to know what @nvkelso and @stepps00 suggest. And of course @nlehuby since you probably have much better local knowledge of these areas than us, your suggestions on what is and isn't valid are appreciated.

Finally, the same situation appears to have happened with the second example, this time with the neighbourhood [Auteuil Sud](https://whosonfirst.mapzen.com/spelunker/id/85873971/).

**Comment by nlehuby** [comment]
Thank you for your analysis.

The limit of the neighborhoods inside the town are approximate, it seems pretty challenging to have them all and ok.
But :
* there seems to be a "Villiers" neighborhood in Villebon-sur-Yvette (but I'm not able to provide a shape for it)
* there is no "Auteuil Sud" neighborhood in Boulogne. But Auteuil is an old city that does not exist anymore and the South of Auteuil (`Auteuil Sud`in French) is now inside the town of Boulogne

I've found a few others cases in the region : is it useful to add them here ?

I guess a neighborhood should not be bigger than its parent county. Do you think we can code something to check all the neighborhood of the region programatically, to fix them all in once ?

**Comment by stepps00** [comment]
Yeah, this will be the case for many of the neighbourhoods in and around Paris. We've opened https://github.com/whosonfirst-data/whosonfirst-data/issues/410 to track updates to Paris neighbourhoods which should fix this issue. Until then, you'll see cases of neighbourhood geometries larger than their parent, cases where neighbourhoods are given an inaccurate hierarchy, etc.

To fix this immediate issue, I can work with the record of Villiers to update it's hierarchy. From what I understand, this neighbourhood record's hierarchy populated Mapzen Search results. Assigning Villiers to Palaiseau instead of Villebon-sur-Yvette through Boundary Issues using `reversegeo:*` properties should solve this issue.

I will update Villiers and paste the commit in here.

Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/410

**Comment by nvkelso** [comment]
For any neighbourhood that’s larger than the parent we can also set it’s
default geom to the label point, and move the existing polygon geom to an
alt geom. It would no longer be eligible for PIPing, but at least the PIP
result would be less bad?

**Comment by stepps00** [comment]
I've updated the record [discussed here](https://github.com/pelias/wof-admin-lookup/issues/179#issue-277836007) and will paste the commit of the fix once complete. 

If that update fixed the issue, I can make additional records to fix the issue [discussed here](https://github.com/pelias/wof-admin-lookup/issues/179#issuecomment-348180447).

**Comment by nlehuby** [comment]
I don't think updating the hierarchy would be a proper fix : the Villiers shape intersects several cities, so this fix will be better for some addresses and worse for others.

I prefer @nvkelso 's proposal to deprecate the geom and don't use it for PIP if it is not accurate.

**Comment by nlehuby** [comment]
any update on this topic ?

**Comment by stepps00** [comment]
Noting here that https://github.com/whosonfirst-data/whosonfirst-data/issues/410 was closed, which corrected the hierarchy issues in Paris Who's On First records.

**Comment by orangejulius** [comment]
I believe this is now fixed:

[/v1/search?text=3 Place Léon Deubel paris](http://pelias.github.io/compare/#/v1/search%3Ftext=3%20Place%20L%C3%A9on%20Deubel%20paris) now shows results in Paris

and

[/v1/search?text=111 Boulevard de Lozère palaiseau](http://pelias.github.io/compare/#/v1/search%3Ftext=111%20Boulevard%20de%20Loz%C3%A8re%20palaiseau) shows results in Palaiseau
